import { readFileSync } from 'node:fs';
import { NAV } from '../../tienda/layout.js';
import { REVIEWS, REELS } from './social.js';
import { GIFTS, BONUS, PLANS, TIMELINE, money } from './data.js';
const A = '/assets/dermafol-brand';
const svg = (body, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${body}</svg>`;
const icons = {
  bag: svg('<path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/>'),
  lock: svg('<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>'),
  check: svg('<path d="m5 12 4 4L19 6"/>'),
  arrow: svg('<path d="M4 12h16m-6-6 6 6-6 6"/>'),
  shield: svg('<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>'),
  truck: svg('<path d="M2 5h12v12H2zm12 5h5l3 4v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>'),
  sun: svg('<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>'),
};
const photo = (name, alt, cls = '', eager = false) => `<img class="${cls}" src="${A}/${name}-960.webp" srcset="${A}/${name}-480.webp 480w, ${A}/${name}-960.webp 960w" sizes="(max-width: 700px) 92vw, 48vw" width="960" height="960" alt="${alt}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
const gallery = [
 ['combo','Kit completo','Combo Dermafol 360°: suplemento, Roll-On y caja'],
 ['funnel3','Sus ingredientes','Los ingredientes del kit Dermafol 360°'],
 ['funnel4','Cómo se usa','La rutina de suplemento y Roll-On'],
 ['funnel6','El protocolo','El protocolo Dermafol 360°']
];
const galleryPhoto = (name,alt,cls='',eager=false) => `<img class="${cls}" src="/assets/dermafol/${name}-880.webp" srcset="/assets/dermafol/${name}-440.webp 440w, /assets/dermafol/${name}-880.webp 880w" sizes="(max-width:700px) 92vw,48vw" alt="${alt}" width="880" height="880" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
const ingredients = [
 ['biotina.webp','Biotina','Vitamina del grupo B','Forma parte del suplemento capilar. Una vitamina relacionada con el metabolismo de nutrientes.'],
 ['colageno.webp','Colágeno hidrolizado','Proteína estructural','Aporta aminoácidos dentro de la fórmula del suplemento.'],
 ['saw-palmetto.webp','Saw Palmetto','Extracto de palma','El componente botánico del suplemento Dermafol.'],
 ['zinc.webp','Zinc','Mineral esencial','Participa en procesos de mantenimiento de tejidos y síntesis de proteínas.'],
 ['vitamina-d3.webp','Vitamina D3','Vitamina liposoluble','Complementa la fórmula nutricional para el cuidado desde adentro.'],
 ['trichogen.jpg','Trichogen','Complejo botánico tópico','El activo del Roll-On para el cuidado localizado del cuero cabelludo, sin minoxidil.']
];
const giftImage = g => `<img src="${A}/${g.id}.webp" alt="${g.name}" width="200" height="200" loading="lazy" decoding="async">`;
const gift = (g, qty, mini = false) => `<div class="gift ${g.level > qty ? 'locked' : ''} ${mini ? 'mini' : ''}" data-gift="${g.id}"><div class="gift-image">${giftImage(g)}${g.level > qty ? `<span class="lock">${icons.lock}</span>` : ''}</div><span class="gift-name">${g.name}</span><del>${money(g.value)}</del><strong>${g.level > qty ? 'CON ' + g.level + ' KITS' : 'INCLUIDO'}</strong></div>`;
const plan = p => `<article class="plan ${p.qty === 3 ? 'selected' : ''}" data-plan-card="${p.qty}">${p.badge ? `<span class="plan-badge ${p.qty === 3 ? 'all' : ''}">${p.badge}</span>` : ''}<label class="plan-label"><input type="radio" name="plan" value="${p.qty}" ${p.qty === 3 ? 'checked' : ''}><span class="radio"></span><span><b>${p.qty} ${p.qty === 1 ? 'kit' : 'kits'}</b><small>${p.label}</small></span><span class="plan-price"><b>${money(p.price)}</b><small>${money(p.unit)} / kit</small></span></label><p class="plan-purpose">${p.qty === 3 ? 'Tu plan de 12 semanas de constancia y seguimiento.' : p.qty === 2 ? 'Dos kits para darle continuidad a tu cuidado.' : 'Conoce los dos pasos de tu nuevo ritual.'}</p><div class="gift-progress"><span>${p.gifts} de 5 regalos desbloqueados</span><b>${money(p.giftValue)} en regalos</b><progress value="${p.gifts}" max="5" aria-label="${p.gifts} de 5 regalos desbloqueados"></progress></div><div class="mini-gifts">${GIFTS.map(g => gift(g, p.qty, true)).join('')}</div></article>`;
const faq = [
  ['¿Qué recibo en cada kit?', 'Un suplemento capilar de 60 cápsulas y un Roll-On de 25 ml. Los regalos se suman una sola vez según el plan de 1, 2 o 3 kits que elijas.'],
  ['¿Cuándo puedo notar cambios?', 'No hay una fecha idéntica para todas. Algunas clientas describen cambios tras varias semanas; la respuesta depende de la causa de la caída y de cada persona. Las 12 semanas son un periodo de seguimiento, no la duración completa del ciclo folicular ni una promesa de crecimiento.'],
  ['¿El Roll-On tiene minoxidil?', 'La versión actual de la marca utiliza Trichogen y no contiene minoxidil. Revisa siempre el etiquetado del producto que recibas.'],
  ['¿Cómo funcionan los regalos?', 'Con 1 kit recibes envío gratis. Con 2 kits sumas perfume capilar y scrunchie. Con 3 kits sumas también termoprotector y reparador de puntas. El pago anticipado añade un gorro de satín a cualquiera de los tres planes. Los colores se entregan según disponibilidad.'],
  ['¿Tengo que pagar antes de recibir?', 'Puedes elegir pago contraentrega o pago anticipado. El envío es gratuito en los dos casos. El gorro de satín es exclusivo del pago anticipado.'],
  ['¿Cómo funciona la garantía de 90 días?', 'La garantía que ofrece Dermafol cubre 90 días. Si no notas cambios en la caída, puedes solicitar a la marca la devolución de tu dinero, sin devolver los frascos. Conserva tu número de pedido para gestionar la solicitud.'],
  ['¿Y si estoy embarazada, lactando o tomo medicamentos?', 'Consulta con tu médico antes de empezar. Si la caída es repentina, aparece en parches o viene con otros síntomas, busca valoración profesional. Este kit no sustituye el diagnóstico ni un tratamiento médico.'],
];
export function renderBrandPage() {
const css = readFileSync(new URL('./style.css', import.meta.url), 'utf8');
const js = readFileSync(new URL('./client.js', import.meta.url), 'utf8');
return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f7f3ee"><meta name="description" content="Descubre el ritual Dermafol 360°. Cuidado capilar por dentro y por fuera, con regalos para acompañar tu constancia."><title>Tu nuevo ritual capilar · Dermafol 360°</title><link rel="icon" href="/assets/marca/dermafol-icono-32.png"><link rel="preload" href="${A}/dm-sans.woff2" as="font" type="font/woff2" crossorigin><style>${css}</style></head><body>
<a class="skip" href="#contenido">Saltar al contenido</a>
<div class="announcement">Un detalle para ti. <a href="#planes">Hasta ${money(117600)} en regalos</a>, incluido el envío gratis.</div>
<header class="header"><details class="brand-menu"><summary aria-label="Abrir navegación">☰</summary><nav aria-label="Menú móvil">${NAV.map(([url,label])=>`<a href="https://www.dermafol.co${url}">${label}</a>`).join('')}<a href="#historias">Historias reales</a><a href="#planes">Elige tu kit</a></nav></details><a class="brand" href="https://www.dermafol.co/" aria-label="Dermafol, inicio"><img src="/assets/marca/dermafol-logotipo.png" width="145" height="49" alt="Dermafol"></a><nav class="desktop-nav" aria-label="Navegación principal">${NAV.map(([url,label])=>`<a href="https://www.dermafol.co${url}">${label}</a>`).join('')}</nav><button class="cart-toggle" data-open-cart aria-label="Abrir mi carrito">${icons.bag}<span>Mi kit</span><b data-cart-count>3</b></button></header>
<main id="contenido">
<section class="hero wrap" data-atidcoa="atencion"><div class="hero-visual"><span class="image-kicker">CUIDADO CAPILAR, POR DENTRO Y POR FUERA.</span>${galleryPhoto('combo',gallery[0][2],'hero-photo',true)}<div class="visual-foot"><span>60 cápsulas + Roll-On 25 ml</span><span>01 / 04</span></div><div class="thumbs" role="group" aria-label="Fotografías del kit">${gallery.map(([name,label,alt],i)=>`<button class="${i===0?'active':''}" data-hero="${name}" aria-label="${label}" aria-pressed="${i===0}">${galleryPhoto(name,alt)}<span>${label}</span></button>`).join('')}</div></div>
<div class="hero-copy"><div class="eyebrow">DERMAFOL 360° · KIT DE CRECIMIENTO</div><h1>Tu cabello merece<br><em>un cuidado completo.</em></h1><p class="intro">Suplemento + Roll-On en un solo kit. Acompaña tu rutina capilar por dentro y por fuera, con regalos para cada etapa.</p><ul class="hero-bullets"><li>${icons.check}Suplemento + Roll-On sin minoxidil</li><li>${icons.check}Una rutina sencilla, mañana y noche</li><li>${icons.check}90 días de garantía para empezar con confianza</li></ul><div class="hero-buy"><div class="buy-heading"><span>ELIGE TU RITUAL</span><a href="#planes">Ver todos los regalos ↗</a></div><div class="quick-plans" role="group" aria-label="Cantidad de kits">${PLANS.map(p=>`<button data-quick-plan="${p.qty}" aria-pressed="${p.qty===3}" class="${p.qty===3?'active':''}"><span>${p.qty} ${p.qty===1?'kit':'kits'}</span><b>${money(p.unit)}<small> / kit</small></b>${p.qty===3?'<i>Todos los regalos</i>':p.qty===2?'<i>Más elegido</i>':'<i>Envío incluido</i>'}</button>`).join('')}</div><div class="hero-gift-box"><div class="hero-gift-heading"><span>TUS REGALOS INCLUIDOS</span><span data-hero-progress>5 de 5 desbloqueados</span></div><progress max="5" value="5" data-hero-progress-bar aria-label="Regalos incluidos en tu kit"></progress><div class="hero-gifts" data-hero-gifts>${GIFTS.map(g=>gift(g,3)).join('')}</div><small>Color según disponibilidad · Pago anticipado: gorro de satín adicional.</small></div><p class="bundle-saving" data-bundle-saving>Ahorras $169.800 frente a comprar 3 kits individuales.</p><div class="hero-total"><strong data-total>${money(249900)}</strong><span><b data-gift-value>${money(117600)}</b> en regalos incluidos</span></div><button class="button full" data-open-cart>Quiero mi ritual <span data-total>${money(249900)}</span>${icons.arrow}</button><div class="trust-inline"><span>${icons.truck}Envío gratis</span><span>${icons.shield}Garantía 90 días</span><span>${icons.lock}Pago a tu elección</span></div></div></div></section>
<div class="brand-line"><div class="brand-line-window"><div class="brand-line-track">${[0,1].map(i=>`<div class="brand-line-group" ${i?'aria-hidden="true"':''}><span>Un poco de constancia.</span><i aria-hidden="true">✳</i><span>Un momento para ti.</span><i aria-hidden="true">✳</i><span>Una nueva relación con tu cabello.</span><i aria-hidden="true">✳</i></div>`).join('')}</div></div><button class="brand-line-pause" aria-label="Pausar cinta animada" aria-pressed="false">Ⅱ</button></div>
<section class="section wrap editorial" data-atidcoa="transformacion"><div><p class="eyebrow">MÁS ALLÁ DEL ESPEJO</p><h2>Que cuidar tu cabello<br>vuelva a sentirse <em>bien.</em></h2><p>El cepillo, la ducha, la raya que miras de cerca. Sabemos que no es solo cabello: también es cómo te sientes contigo.</p><p>Dermafol reúne el cuidado interno y externo en un mismo kit. Para que tu siguiente paso tenga una rutina, en lugar de otro producto suelto.</p><a class="text-link" href="#ritual">Conoce tus dos pasos ${icons.arrow}</a></div><div class="editorial-photo">${photo('mujer-producto','Mujer sosteniendo su producto Dermafol')}<span class="photo-caption">El cuidado empieza con un momento para ti.</span></div></section>
<section class="section soft" id="ritual" data-atidcoa="interes"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">EL MÉTODO DERMAFOL 360°</p><h2>Dos pasos.<br><em>Un mismo propósito.</em></h2></div><p>Un suplemento y un Roll-On, pensados para acompañarse en tu rutina de cuidado capilar.</p></div><div class="duo"><article class="ritual-card">${photo('suplemento-abierto','Suplemento Dermafol con cápsulas')}<div class="ritual-copy"><span class="step">01 / DESDE ADENTRO</span><h3>Nutre tu rutina.</h3><p>60 cápsulas con Saw Palmetto, Zinc, Vitamina D3, Biotina y Colágeno hidrolizado.</p><div class="ritual-note">${icons.sun}<span>Tu momento de la mañana<br><small>Sigue las indicaciones del envase.</small></span></div></div></article><article class="ritual-card"><div class="rollon-product-photo"><img src="/assets/dermafol-brand/rollon-producto.webp" width="282" height="332" alt="Roll-On Dermafol de 25 ml" loading="lazy" decoding="async"></div><div class="ritual-copy"><span class="step">02 / DESDE AFUERA</span><h3>Cuida desde la raíz.</h3><p>Roll-On de 25 ml con Trichogen. Aplicación localizada para completar tu ritual.</p><div class="ritual-note">${icons.sun}<span>Un momento para tu cuero cabelludo<br><small>Aplica y masajea según el etiquetado.</small></span></div></div></article></div></div></section>
<section class="section wrap" id="ingredientes"><div class="section-heading"><div><p class="eyebrow">CONOCE TU FÓRMULA</p><h2>Lo que hay dentro<br><em>también importa.</em></h2></div><p>Cinco ingredientes en el suplemento. Un complejo botánico en el Roll-On. Conoce cada parte de tu cuidado.</p></div><div class="ingredient-grid">${ingredients.map(([img,name,tag,text],i)=>`<article class="ingredient-card"><div><img src="/assets/dermafol/ing/${img}" alt="${name}" width="400" height="300" loading="lazy" decoding="async"><span>0${i+1}</span></div><p class="eyebrow">${tag}</p><h3>${name}</h3><p>${text}</p></article>`).join('')}</div></section>
<section class="section wrap" id="progreso" data-atidcoa="deseo"><div class="section-heading"><div><p class="eyebrow">DALE TIEMPO A TU CABELLO</p><h2>Tu progreso tiene<br><em>su propio ritmo.</em></h2></div><p>12 semanas para construir el hábito, observar y hacer un balance. Así puedes acompañar cada etapa.</p></div><div class="timeline-tabs" role="tablist" aria-label="Etapas de tu rutina">${TIMELINE.map((t,i)=>`<button role="tab" id="tab-${i}" aria-controls="stage-${i}" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}" data-stage="${i}"><span>0${i+1}</span>${t.label}</button>`).join('')}</div>${TIMELINE.map((t,i)=>`<div class="timeline-panel" role="tabpanel" id="stage-${i}" aria-labelledby="tab-${i}" ${i?'hidden':''}><div class="timeline-image">${photo(t.image,t.title)}</div><div class="timeline-copy"><p class="eyebrow">${t.tag}</p><h3>${t.title}</h3><p>${t.text}</p><div class="tip">${icons.check}<span>${t.tip}</span></div></div></div>`).join('')}<p class="fine">Los resultados son individuales. Esta guía de seguimiento no garantiza crecimiento ni sustituye una valoración dermatológica.</p></section>
<section class="section cocoa" id="regalos"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">UN EXTRA DE CUIDADO, DE NUESTRA PARTE</p><h2>Tu constancia merece<br><em>unos buenos detalles.</em></h2></div><p>Elige tu plan y voltea sus cartas. Cada una revela un regalo incluido en tu ritual.</p></div><div class="game-head"><span data-game-status aria-live="polite">0 de 5 regalos descubiertos</span><button class="subtle-light" data-reveal-all>Revelar mis regalos ↗</button></div><div class="gift-game">${GIFTS.map((g,i)=>`<button class="gift-card" data-reveal="${i}" aria-label="Descubrir regalo ${i+1}" aria-pressed="false"><span class="card-inner"><span class="card-front"><span class="card-number">0${i+1}</span><span class="card-logo">Dermafol</span><span class="card-flower">✳</span><span class="card-instruction">Toca para descubrir</span></span><span class="card-back">${giftImage(g)}<b>${g.name}</b><del>${money(g.value)}</del><strong>INCLUIDO</strong></span></span></button>`).join('')}</div><p class="game-note">Regalos garantizados según tu plan, no al azar. <a href="#planes">Cambia de plan para desbloquear más.</a></p><div class="bonus-bar"><div>${giftImage(BONUS)}</div><p><span>UN REGALO MÁS POR ADELANTARTE</span><b>Elige pago anticipado y suma un gorro de satín.</b><small>En cualquier plan · valor ${money(BONUS.value)}</small></p><a href="#planes" class="bonus-link">Lo quiero ${icons.arrow}</a></div></div></section>
<section class="section wrap" id="planes" data-atidcoa="accion"><div class="center heading"><p class="eyebrow">TU RITUAL, A TU MEDIDA</p><h2>Más constancia.<br><em>Más regalos para ti.</em></h2><p>Cada kit incluye suplemento de 60 cápsulas + Roll-On de 25 ml.<br>El envío va por nuestra cuenta en cualquier plan.</p></div><div class="plans">${PLANS.map(plan).join('')}</div><div class="payment-box"><div><p class="eyebrow">TÚ ELIGES CÓMO PAGAR</p><h3>Al recibir o por anticipado.</h3></div><fieldset class="payment-options"><legend class="sr-only">Método de pago</legend><label><input type="radio" name="payment" value="cod" checked><span>${icons.truck}<b>Pago contraentrega</b><small>Pagas cuando llegue a tu casa</small></span></label><label><input type="radio" name="payment" value="online"><span>${icons.lock}<b>Pago anticipado</b><small>+1 regalo: gorro de satín</small></span></label></fieldset><div class="bonus-preview" data-bonus>${giftImage(BONUS)}<div><b>Gorro de satín</b><del>${money(BONUS.value)}</del><strong data-bonus-label>Se desbloquea con pago anticipado</strong></div><span class="bonus-icon">${icons.lock}</span></div></div><div class="offer-footer"><div><span>Total de tu ritual</span><strong data-total>${money(249900)}</strong><small>Envío gratis · <span data-gift-value>${money(117600)}</span> en regalos</small></div><button class="button" data-open-cart>Añadir mi ritual al carrito ${icons.arrow}</button></div><p class="fine center">Accesorios: color según disponibilidad. Imágenes ilustrativas de los regalos; su presentación puede variar. Precios en pesos colombianos.</p></section>
<section class="section soft" id="historias" data-atidcoa="confianza"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">HISTORIAS QUE YA NOS ACOMPAÑAN</p><h2>Ellas lo cuentan<br><em>con sus palabras.</em></h2></div><p>Experiencias publicadas por clientas de Dermafol. Cada historia es personal; los resultados pueden variar.</p></div><div class="reel-row">${REELS.map(({poster,url},i)=>`<div class="reel"><video controls playsinline preload="none" poster="${poster}" aria-label="Video de la comunidad Dermafol ${i+1}"><source data-src="${url}" type="video/mp4"></video><button class="reel-play" aria-label="Reproducir video ${i+1}"><span>▷</span>Ver su historia</button></div>`).join('')}</div><p class="rail-hint">Desliza para ver más historias →</p><div class="testimonials">${REVIEWS.map(({name,city,quote,image},i)=>`<figure class="review" ${i>=6?'data-more-review hidden':''}><img class="review-photo" src="${image}" alt="Foto compartida por ${name}" width="420" height="336" loading="lazy" decoding="async"><blockquote>“${quote}”</blockquote><figcaption><span><b>${name}</b><small>${city} · Testimonio publicado en Dermafol</small></span></figcaption></figure>`).join('')}</div><button class="reviews-more" data-more-reviews>Ver las ${REVIEWS.length} historias de la comunidad ${icons.arrow}</button></div></section>
<section class="section wrap guarantee" data-atidcoa="objeciones"><div class="guarantee-seal"><span>DERMAFOL</span><strong>90</strong><span>DÍAS DE GARANTÍA</span></div><div><p class="eyebrow">UN COMIENZO CON TRANQUILIDAD</p><h2>Date la oportunidad.<br><em>Nosotros ponemos la garantía.</em></h2><p>Si no notas cambios en la caída durante los 90 días de garantía, solicita la devolución de tu dinero. Sin devolver los frascos.</p><a href="#faq" class="text-link">Resuelve tus dudas ${icons.arrow}</a></div></section>
<section class="section soft" id="faq"><div class="wrap faq-layout"><div><p class="eyebrow">ANTES DE EMPEZAR</p><h2>Todo claro.<br><em>Desde el primer día.</em></h2><p>Lo que necesitas saber para elegir tu ritual.</p></div><div>${faq.map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>
<section class="final-cta wrap"><p class="eyebrow">EL SIGUIENTE PASO ES PARA TI</p><h2>Haz espacio para<br><em>tu nuevo ritual.</em></h2><button class="button" data-open-cart>Empezar con Dermafol ${icons.arrow}</button><p>Envío gratis · Contraentrega o pago anticipado · Garantía 90 días</p></section>
</main><footer class="brand-footer"><div class="wrap footer-grid"><div><img src="/assets/marca/dermafol-logotipo.png" width="150" height="50" alt="Dermafol"><p>Cuidado capilar por dentro y por fuera.<br>Una marca de VERA &amp; CO.</p></div>${[
['Productos',[['/producto/combo-dermafol-360','Combo Dermafol 360°'],['/producto/suplemento-capilar','Suplemento capilar'],['/producto/roll-on-dermoestimulante','Roll-On'],['/combos','Combos y ahorro']]],
['Dermafol',[['/nosotros','Sobre nosotros'],['/guias','Guías y contenido'],['/preguntas-frecuentes','Preguntas frecuentes']]],
['Estamos para ti',[['/contacto','Contacto y ayuda'],['/seguimiento','Seguir mi pedido'],['/politicas/envios','Envíos y entregas'],['/politicas/devoluciones','Cambios y devoluciones']]]
].map(([title,links])=>`<div><h3>${title}</h3>${links.map(([url,label])=>`<a href="https://www.dermafol.co${url}">${label}</a>`).join('')}</div>`).join('')}</div><div class="wrap footer-legal"><span>© ${new Date().getFullYear()} Dermafol · VERA &amp; CO</span><div><a href="https://www.dermafol.co/politicas/privacidad">Privacidad</a><a href="https://www.dermafol.co/politicas/datos">Tratamiento de datos</a><a href="https://www.dermafol.co/politicas/terminos">Términos</a></div></div></footer>
<div class="sticky-buy"><div><b data-plan-label>3 kits · todos los regalos</b><span><strong data-total>${money(249900)}</strong> <small>Envío gratis</small></span></div><button class="button" data-open-cart>Elegir mi ritual ${icons.arrow}</button></div>
<dialog class="cart" id="cart" aria-labelledby="cart-title"><div class="cart-header"><div><span class="eyebrow">UN MOMENTO PARA TI</span><h2 id="cart-title">Tu ritual Dermafol.</h2></div><button class="close-cart" aria-label="Cerrar carrito">×</button></div><div class="cart-scroll"><div class="cart-product">${photo('kit-caja','Kit Dermafol 360°')}<div><h3>Kit Dermafol 360°</h3><p>Suplemento + Roll-On</p><label for="cart-qty">Cantidad de kits</label><select id="cart-qty">${PLANS.map(p=>`<option value="${p.qty}" ${p.qty===3?'selected':''}>${p.qty} ${p.qty===1?'kit':'kits'} · ${money(p.price)}</option>`).join('')}</select></div></div><div class="cart-progress"><b data-progress-label>5 de 5 regalos desbloqueados</b><progress max="5" value="5" data-progress aria-label="Regalos desbloqueados"></progress><p data-upsell>Ya tienes todos los regalos de tu plan.</p></div><div class="cart-gifts" data-cart-gifts></div><fieldset class="cart-pay"><legend>¿Cómo prefieres pagar?</legend><label><input type="radio" name="cart-payment" value="cod" checked>Contraentrega <small>Pagas al recibir</small></label><label><input type="radio" name="cart-payment" value="online">Pago anticipado <small>+ gorro de satín</small></label></fieldset><div class="cart-bonus" data-cart-bonus></div><div class="cart-trust">${icons.shield}<p><b>Tu compra, con tranquilidad.</b><br>90 días de garantía · Envío gratis<br>Elige cuándo pagar.</p></div><form id="brand-checkout" hidden><h3>Datos de entrega</h3><p class="preview-notice">Vista previa privada: puedes probar el formulario. No se enviarán pedidos ni se realizarán cobros.</p><label>Nombre y apellido<input name="customer_name" autocomplete="name" required></label><label>Celular / WhatsApp<input name="phone" autocomplete="tel" inputmode="tel" pattern="(?:\\+?57\\s?)?[0-9\\s]{10,14}" required></label><div class="fields"><label>Departamento<select name="department" required><option value="">Elige…</option></select></label><label>Ciudad<select name="city" required disabled><option value="">Elige…</option></select></label></div><label>Dirección<input name="address" autocomplete="street-address" minlength="6" required></label><label class="consent"><input type="checkbox" required>Confirmo los datos de entrega de mi pedido.</label><button class="button full" type="submit">Probar confirmación ${icons.arrow}</button><p class="form-message" role="status"></p></form></div><div class="cart-footer"><div class="cart-totals"><span>Envío <b>GRATIS</b></span><span>Regalos incluidos <b data-gift-value>${money(117600)}</b></span><span class="total">Total <b data-total>${money(249900)}</b></span></div><button class="button full" id="continue-checkout">Continuar con mi pedido ${icons.arrow}</button><p>${icons.lock}<span data-pay-note>Pagas al recibir. Sin pago previo.</span></p></div></dialog>
<div class="toast" role="status" aria-live="polite"></div><script>window.DERMAFOL_BRAND=${JSON.stringify({plans:PLANS,gifts:GIFTS,bonus:BONUS,assetBase:A,privatePreview:true})};</script><script>${js}</script></body></html>`;
}
